### PR TITLE
Remove UTF8 BOM Marker when reading token file

### PR DESCRIPTION
**Pull request by DasAng**
This is a fix to solve #3

### CODE REVIEW

**Comment by pankajku** [comment]
Hi There,

This is Pankaj Kumar from ClusterHQ.
Thanks for identifying and fixing the issue. I have reviewed the fix and it makes perfect sense.

**Comment by wallnerryan** [comment]
Thanks @DasAng We'll work ing getting this fix in or getting a review for possible changes soon!

**Comment by pankajku** [comment]
Hi @DasAng ,

We reviewed your fix and decided to address it in multiple ways:

1. The GUI shouldn't allow BOM to be included in the downloadable token file.

2. There is always a possibility of introducing control characters while a user opens the file in an editor or moves around across machines. So we wrote code in the client that trim the token of all control and extended bytes.

You made a valuable contribution by being one of the very first users to identify and analyze the issue and come up with a working solution.

Best Regards,
Pankaj.

**Comment by DasAng** [comment]
@pankajku That is good to hear :)

**Comment by pankajku** [comment]
Closing the PR as the issue has been resolved.

**Comment by pankajku** [comment]
Closing the PR as the issue has been resolved.

**Comment by ferrantim** [comment]
Hey @DasAng really appreciate this PR.  If you send me an email at michael at clusterhq.com, I'll send you a FlockerHub tshirt.  Thanks!

**Pull request closed without merging**
